### ISSUE TITLE
Register SampleData for Density Analysis

### ISSUE THREAD

**Issue by jcfr** [WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis#17]
![image](https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/assets/219043/e62792cf-a121-42f6-9a60-42484f54b7cd)

**Comment by jszatkowski116** [comment]
There is no sample data needed specifically for Density Analysis, as it is designed to work with any bone type. The tests and tutorial are able to just reuse the cancellous bone sample data.
